### ISSUE TITLE
Omnizart Not being installed in Collab

### ISSUE THREAD

**Issue by magneto514** [Music-and-Culture-Technology-Lab/omnizart#100]
Hi,

I tried running the code in the provided collab notebook. It looks like omnizart is failing to install as seen below - can you please advice how to proceed?

Collecting git+https://github.com/Music-and-Culture-Technology-Lab/omnizart.git
  Cloning https://github.com/Music-and-Culture-Technology-Lab/omnizart.git to /tmp/pip-req-build-56mn6sy7
  Running command git clone --filter=blob:none --quiet https://github.com/Music-and-Culture-Technology-Lab/omnizart.git /tmp/pip-req-build-56mn6sy7
  Resolved https://github.com/Music-and-Culture-Technology-Lab/omnizart.git to commit e047d27b3137ef335f2040106ff92f9669d2395a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click<8.0.0,>=7.1.2 (from omnizart==0.5.0)
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 kB 1.9 MB/s eta 0:00:00
Collecting jsonschema<4.0.0,>=3.2.0 (from omnizart==0.5.0)
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 6.4 MB/s eta 0:00:00
Collecting librosa<0.9.0,>=0.8.0 (from omnizart==0.5.0)
  Downloading librosa-0.8.1-py3-none-any.whl (203 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.8/203.8 kB 6.8 MB/s eta 0:00:00
Requirement already satisfied: madmom<0.17.0,>=0.16.1 in /usr/local/lib/python3.10/dist-packages (from omnizart==0.5.0) (0.16.1)
Collecting mir_eval<0.7,>=0.6 (from omnizart==0.5.0)
  Downloading mir_eval-0.6.tar.gz (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 kB 8.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pillow<9.0.0,>=8.3.2 (from omnizart==0.5.0)
  Downloading Pillow-8.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 12.5 MB/s eta 0:00:00
Collecting pretty_midi<0.3.0,>=0.2.9 (from omnizart==0.5.0)
  Downloading pretty_midi-0.2.10.tar.gz (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 26.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pyfluidsynth<2.0.0,>=1.2.5 (from omnizart==0.5.0)
  Downloading pyFluidSynth-1.3.2-py3-none-any.whl (19 kB)
Collecting pyyaml<6.0.0,>=5.3.1 (from omnizart==0.5.0)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 15.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  **error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
/bin/bash: line 1: omnizart: command not found**

Thanks

**Comment by SutirthaChakraborty** [comment]
Still not working in Colab. @yoyololicon Please check

**Comment by BreezeWhite** [comment]
Currently there is no easy fix to the issue. The root cause is that colab now defaults to use Python 3.10, which breaks the underlying packages' requirements of python version. I've tried to fix the python version by using miniconda, but that would further break other dependencies, too.

**Comment by BreezeWhite** [comment]
I've figure out the solution and colab should work now.

**Comment by SutirthaChakraborty** [comment]
@BreezeWhite how?

**Comment by BreezeWhite** [comment]
@SutirthaChakraborty It's mainly about adjusting the python version from 3.10 to 3.8, and also fix some other bugs. You can see the code for more details.
