### ISSUE TITLE
Can the MIDI produce a Guitar instead of Piano staff? 

### ISSUE THREAD

**Issue by tzolov** [Music-and-Culture-Technology-Lab/omnizart#13]
This more of a question. 

I've tested the tool with guitar wav and it seems to do well.  

But the output MIDI is for Piano (e.g. 2 staffs). Is it possible to configure the output for a single (guitar) staff? 
I am not that familiar with MIDI and i'm not sure if the instrument/staff structure is a MIDI "thing" or is related to the way the `omnizart` outputs the result.

**Comment by BreezeWhite** [comment]
I'm not sure if I understand your question correctly, but I supposed you executed `omnizart chord transcribe test.wav` and then synthesized the output MIDI with `omnizart synth test.mid`, hearing that the sound is played with piano and not guitar, which you expected to be. 

If I understand right, the reply would be that there is currently no way to configure the output MIDI to use the guitar soundfont.
But you can use the generated CSV file, which records the information of transcribed chords, to generate the guitar audio.
