### ISSUE TITLE
Is there a way to speed up transcribing by using the GPU ?

### ISSUE THREAD

**Issue by AntoineGermanique** [Music-and-Culture-Technology-Lab/omnizart#14]
Hi, I guess the question is in the title. Really like this library, would be great if it could use GPU to make things faster.

Thanks for your work 👍

**Comment by BreezeWhite** [comment]
Thank you for the encouraging. We are happy this work helps your day.

For your question, the answer is **Yes**. You only need to `pip install tensorflow-gpu` or use the provided docker image, which is already GPU enabled version.

If you still have any problem using `omnizart`, feel free to contact us or open issues.

**Comment by 00sapo** [comment]
For me, this is not enough. Also, I needed to install `tensorflow-gpu==3.2.0 `, otherwise, poetry complains about conflicts due to `omnizart` dependencies
