### ISSUE TITLE
AttributeError: type object 'AudioAdapter' has no attribute 'default'

### ISSUE THREAD

**Issue by dianxin556** [Music-and-Culture-Technology-Lab/omnizart#16]
when I load a sample wav with load_audio() API , an error occur like this:AttributeError: type object 'AudioAdapter' has no attribute 'default'.

**Comment by BreezeWhite** [comment]
Please upgrade to v0.3.2 and it should work now.
Sorry for causing the inconvenience.

**Comment by dianxin556** [comment]
Thanks,I will try!
