### ISSUE TITLE
Enhancement: Add a spleeter pipeline to the colab document 

### ISSUE THREAD

**Issue by tandy-1000** [Music-and-Culture-Technology-Lab/omnizart#21]
To improve the performance of the transcription model, it would help to be able to use spleeter's source separation, especially when transcribing specific tracks, such as guitar only.

It is understandable that this document is to demo omnizart, but it is worth considering.

**Comment by BreezeWhite** [comment]
Hi, could you describe in more detail what scenario you are facing? What module are you using? The `chord` module or `music` module?
We do use Spleeter in the `vocal` module for separating the vocal track first, then transcribe the pitch after the separation. If you'd like, you can edit the colab to totally achieve what you've mentioned I think. For me, I would expect the colab providing only simple functionalities.

**Comment by tandy-1000** [comment]
I wanted to use omnizart to transcribe only a specific track with the `piano` model, but I ended up editing the colab, it makes sense to not include this in the demo.
