### ISSUE TITLE
Music-Piano in colab runs into shape mismatch error

### ISSUE THREAD

**Issue by AlxDfy** [Music-and-Culture-Technology-Lab/omnizart#23]
Using the colab notebook linked in https://music-and-culture-technology-lab.github.io/omnizart-doc/ (https://bit.ly/omnizart-colab) results in a value error (attached) but only when the 'Music-Piano' mode is selected regardless of if uploaded via MP3 or Youtube link 
![image](https://user-images.githubusercontent.com/4674698/120520310-7cb2e700-c388-11eb-977f-775310bd7f65.png)
![image](https://user-images.githubusercontent.com/4674698/120519727-cd761000-c387-11eb-91c1-2590fcea9214.png)

**Comment by BreezeWhite** [comment]
Oops...
I'll fix it as soon as possible and update to the next version.
Thank you for reporting the bug.

**Comment by AlxDfy** [comment]
Thank you! 

Unfortunately, still running into the same bug on my end:
![image](https://user-images.githubusercontent.com/4674698/120722381-7d30a800-c484-11eb-8cdb-7a99b9064f67.png)

**Comment by BreezeWhite** [comment]
The patch is currently in dev branch and haven't merged into master. I plan to publish the patched version today after fixing some other minor bugs.

**Comment by BreezeWhite** [comment]
I have published a new version and it should work now. There are now two models for piano transcription, and they have different transcription performance that it's hard to judge which one is better. If you are willing, please give some feedback on these models. I'll be very appreciate^^

**Comment by AlxDfy** [comment]
Thank you!
The omnizart/checkpoints/music/music_piano model is surprisingly good!
It has trouble when there are vocals overlaid with instruments causing it to try and play both as opposed to harmonizing the two into a singular 'nice' sounding sound; but certainly a great start!
