### ISSUE TITLE
My comments on `paper.md`

### ISSUE THREAD

**Issue by keunwoochoi** [Music-and-Culture-Technology-Lab/omnizart#25]
Hi, I'm one of the JOSS reviewers of this repo. Before checking the software side of the work, I'd like to leave my comments on the paper here. I read this version (https://github.com/openjournals/joss-reviews/issues/3218#issuecomment-855172230) of the paper. I noticed it's a bit updated but not the part I'd like to mention about. 

---

`L11-14`: It's a bit long, making the sentence slightly vague. 

`L25-26`: What do you mean exactly by "multifaceted nature"? This can be clarified.

`L29`: "previous solution" -> "previous solutions". Also, maybe some citations of the solutions?

`L30-31`: I think this sentences can be re-written a bit to clarify. The current one confused me a bit.

`L34-35`: I found this sentence out of context a little. Wouldn't it make more sense to mention it in the first paragraph of "Statement of need"?

`L36-37`: -> "..original papers. The models can.."

`L56-58`: Really? But how much instrument-agnostic is it?

`L61-62`: "which predicts percussive events from a given input audio." → probably no need to mention? This is assumed in the definition of drum transcription.

`L69-70`: It sounds like the pitch extractor not a "module" while note segmentation is, and that confuses me.

`L76` : "The training includes.." → "The training data includes.."

`L80`: "function" → probably, keep using "model" for consistency?

`L109`: remove "also".

---

Best,
Keunwoo

**Comment by faroit** [comment]
just for the referencing: the review issue is here: https://github.com/openjournals/joss-reviews/issues/3347

**Comment by keunwoochoi** [comment]
> just for the referencing: the review issue is here: [openjournals/joss-reviews#3347](https://github.com/openjournals/joss-reviews/issues/3347)

oops, i think @faroit  you meant "https://github.com/openjournals/joss-reviews/issues/3391" this. but you mean, comments like this are supposed to be communicated at the review thread?

**Comment by faroit** [comment]
@keunwoochoi yes, sure, sorry. copy-pasted the wrong link....

> but you mean, comments like this are supposed to be communicated at the review thread?

No, its exactly how it's supposed to be :+1:
I was just linking to the review issue, since you started reviewing before the official review even started ;-)

**Comment by keunwoochoi** [comment]
(Pinging @BreezeWhite in case you missed it)

**Comment by BreezeWhite** [comment]
Hi, sorry for the late update.It's been busy these days. 

For issue 2-5: We decide to rewrite the whole "Statement of need" section as can been seen in the updated version.

For L56-58:  We understand your concern. Following the definition in the original paper, the term “instrument agnostic” means that the instrument classes in the input can be “uninformed” and we truly did not mean that the model can predict “unseen” instrument classes. To avoid misleading, we guide the readers to read the [reference paper](https://drive.google.com/file/d/1q9SvH7Ozo3l3cEIFJdR-5kfjY_0j6SbE/view?usp=sharing)
 
For L69-L70: The system for vocal transcription contains a pitch extraction and a note segmentation module.

Thanks for pointing out the above issues. Please check if there are still needs to modify.
