### ISSUE TITLE
References in the documentation contain footnotes as well

### ISSUE THREAD

**Issue by hagenw** [Music-and-Culture-Technology-Lab/omnizart#27]
When going to https://music-and-culture-technology-lab.github.io/omnizart-doc/#references
one sees

![image](https://user-images.githubusercontent.com/173624/124786600-236e4280-df48-11eb-9ca3-ac8e6a77c501.png)

which is a strange mix of references (using sphinxcontrib.bibtex) and sphinx footnotes.

I guess all of them should be references?

**Comment by BreezeWhite** [comment]
Hi, thanks for pointing out. Seems like I forgot to remove the redundant references. It's been removed now.

**Comment by keunwoochoi** [comment]
(Commenting to link this to https://github.com/openjournals/joss-reviews/issues/3391)

**Comment by hagenw** [comment]
Looks good now.
