### ISSUE TITLE
Missing footnote for music example on landing page of documentation

### ISSUE THREAD

**Issue by hagenw** [Music-and-Culture-Technology-Lab/omnizart#28]
When going to https://music-and-culture-technology-lab.github.io/omnizart-doc and scrolling to the usage examples one can see

![image](https://user-images.githubusercontent.com/173624/124787188-9bd50380-df48-11eb-8c2b-eeff79c727c5.png)

But there is no further explanation for the `*` footnote.

**Comment by BreezeWhite** [comment]
Hi, thanks for pointing out. This is a typo, and not actually referencing anything.

**Comment by keunwoochoi** [comment]
(Commenting to link this to https://github.com/openjournals/joss-reviews/issues/3391)

**Comment by hagenw** [comment]
Fixed, as "*" is removed now.
