### ISSUE TITLE
Installation issues under Linux due to vamp

### ISSUE THREAD

**Issue by hagenw** [Music-and-Culture-Technology-Lab/omnizart#29]
As mentioned already in https://github.com/Music-and-Culture-Technology-Lab/omnizart/issues/26 the straightforward installation with `pip` can fail due to `vamp`.

I got under Ubuntu 18.04 using Python 3.6.9:

```bash
$ pip install omnizart
...
ERROR: Cannot install omnizart==0.1.0, omnizart==0.1.1, omnizart==0.2.0, omnizart==0.3.0, omnizart==0.3.1, omnizart==0.3.2, omnizart==0.3.3, omnizart==0.3.4, omnizart==0.4.0 and omnizart==0.4.1 because these package versions have conflicting dependencies.
```

Installing `numpy` manually first as proposed in https://github.com/Music-and-Culture-Technology-Lab/omnizart/issues/26 does indeed solve this issue. I'm not completely sure if this can be solved by putting `numpy` as a direct dependency to `setup.py` as proposed in https://github.com/Music-and-Culture-Technology-Lab/omnizart/issues/26, but maybe you can try. Otherwise please expand the installation instructions accordingly.

**Comment by BreezeWhite** [comment]
I've tried to explicitly put `numpy` as the dependency, but seems not work. I've updated the documentation to inform users to install `numpy` and `Cython` before installing `omnizart`.

**Comment by keunwoochoi** [comment]
(Commenting to link this to https://github.com/openjournals/joss-reviews/issues/3391)

**Comment by hagenw** [comment]
Thanks.
