### ISSUE TITLE
Installation of madmom requires cython

### ISSUE THREAD

**Issue by hagenw** [Music-and-Culture-Technology-Lab/omnizart#30]
I stumbled over the same problem under Linux and Python 3.6.9 as described in #26.

I would recommend to extend the installation instructions and mention that the user need to install `Cython` first.

**Comment by BreezeWhite** [comment]
Documentation has been updated to require users install `Cython` before installing `omnizart`.

**Comment by keunwoochoi** [comment]
(Commenting to link this to https://github.com/openjournals/joss-reviews/issues/3391)

**Comment by hagenw** [comment]
Thanks.
