### ISSUE TITLE
Header image of documentation landing page does not scale

### ISSUE THREAD

**Issue by hagenw** [Music-and-Culture-Technology-Lab/omnizart#31]
Go to https://music-and-culture-technology-lab.github.io/omnizart-doc

At the top of the page under the heading you have a picture, which is not a bad idea.
But in this case it would be better if the picture would scale to the actual viewing size.

For me it looks like this at the moment:

![image](https://user-images.githubusercontent.com/173624/124788999-2ec26d80-df4a-11eb-8b72-6d01dc469c58.png)

It's also not a good idea on a mobile phone, where it looks like this for me:

![image](https://user-images.githubusercontent.com/173624/124789133-4ac60f00-df4a-11eb-90c0-d323f0b4f970.png)

**Comment by BreezeWhite** [comment]
Hi, thanks for pointing out. The bug should be fixed now.

**Comment by keunwoochoi** [comment]
(Commenting to link this to https://github.com/openjournals/joss-reviews/issues/3391)

**Comment by hagenw** [comment]
Indeed, looks good now :+1:
