### ISSUE TITLE
Provide music example as WAV not embedded youtube video

### ISSUE THREAD

**Issue by hagenw** [Music-and-Culture-Technology-Lab/omnizart#34]
In order to verify if `omnizart` produces the same output as reported in the docs a user needs to first figure out how to download the youtube video (e.g. `youtube-dl https://www.youtube.com/watch?v=hjJhweRlE-A` under Ubuntu 18.04. is not working for me).

If the license would allow for it, it would be nice to include the original sound file as WAV as well.

**Comment by BreezeWhite** [comment]
We've provided the full extraction results below the Youtube video. The [link](https://drive.google.com/file/d/15VqHearznV9L83cyl61ccACsXXJ4vBHo/view?usp=sharing) can be found in the description. The file can be downloaded and opened with Audacity. It contains all the tracks as shown on the main page.
There is also an additional [demo page](https://music-and-culture-technology-lab.github.io/omnizart-doc/demo.html), providing more results for comparison, and all the tracks can be downloaded from the [documentation repository](https://music-and-culture-technology-lab.github.io/omnizart-doc).

**Comment by hagenw** [comment]
Yes, you are right, this is indeed sufficient.
