### ISSUE TITLE
CONTRIBUTING includes broken link to docs

### ISSUE THREAD

**Issue by hagenw** [Music-and-Culture-Technology-Lab/omnizart#36]
In `CONTRIBUTING.md` it states:

```
[Hosted document page](http://140.109.21.96:8000/build/html/index.html)
```

But [Hosted document page](http://140.109.21.96:8000/build/html/index.html) is not reachable,
and should most likely be pointing to https://music-and-culture-technology-lab.github.io/omnizart-doc/index.html

**Comment by BreezeWhite** [comment]
Oops, I forgot to update the URL. It was written when there was no documentation page yet.

**Comment by BreezeWhite** [comment]
The link has been fixed.

**Comment by hagenw** [comment]
Thanks.
