### ISSUE TITLE
JOSS editorial review: bibliography

### ISSUE THREAD

**Issue by faroit** [Music-and-Culture-Technology-Lab/omnizart#49]
I found inconsistencies in the bibliography when it comes e.g. Proceedings of ISMIR. I suggest to have all bib entries use:

```
booktitle = {Proceedings of the International Society for Music Information Retrieval Conference ({ISMIR})}
```

https://github.com/openjournals/joss-reviews/issues/3391

**Comment by BreezeWhite** [comment]
Thanks for the detailed review. I've merged the corresponding pull request.

**Comment by faroit** [comment]
@BreezeWhite sorry, but this wasn't related to #48. 

- please reopen this issue
- go over the bibliography as suggested above
- close when done

**Comment by BreezeWhite** [comment]
@faroit oops, sorry for that :joy: I've fixed the issue according to your suggestion, and additionally checked other inconsistency in the bibliography. Changes can be viewed from [the commit](https://github.com/Music-and-Culture-Technology-Lab/omnizart/commit/3aecfb5b87c59dc2c6011a35f46834cde98c4127).

**Comment by faroit** [comment]
looks good. Thanks! :-)
