### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by PSCM** [Music-and-Culture-Technology-Lab/omnizart#52]
Sorry for the naive question, but is there any way to apply the methods to multiple files (batch)?

**Comment by BreezeWhite** [comment]
Do you mean batch transcribe? Currently you can only feed one single source. If you want to transcribe multiple songs at a time, you have to write the parallel mechanism to do it.

**Comment by PSCM** [comment]
Yes. Do you have any suggestions on how to make this mechanism, please? All my attempts didn't work.

**Comment by BreezeWhite** [comment]
I have a simple idea that can help you to do it sequentially. It's a simple shell script that process through all files under the folder.
``` bash
#!/bin/bash

for i in "$1"/*
do
  omnizart transcribe chord "$i"
done
```
Something like above. Though it is not parallel but sequential.

**Comment by PSCM** [comment]
Thank you for your help! One last question, if I may. I'm not familiar with shell and when I try to run your code I get this error: 

Invalid value for 'INPUT_AUDIO': Path 'chord' does not exist. 

I'm running on Colab.

**Comment by PSCM** [comment]
Thank you for your help! I just changed the order of the parameters:
omnizart chord transcribe instead of omnizart transcribe chord

**Comment by BreezeWhite** [comment]
Oops, sorry for the typo. Glad to hear that^^
