### ISSUE TITLE
Colab link on README not working

### ISSUE THREAD

**Issue by nyanpasu64** [Music-and-Culture-Technology-Lab/omnizart#55]
Right now when I try running the model using the Colab link, I get the same error as https://github.com/Music-and-Culture-Technology-Lab/omnizart/issues/47#issuecomment-981630546:

```
UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[node model_1/conv2d_1/Conv2D (defined at /usr/local/lib/python3.7/dist-packages/omnizart/music/prediction.py:183) ]] [Op:__inference_predict_function_135953]

Function call stack:
predict_function
```

Should the colab link be (temporarily?) removed or demoted in the README, so people coming to this project won't waste their time trying to set it up, and run into this issue?

**Comment by BreezeWhite** [comment]
The discussion below the issue suggests changing the runtime to TPU. That should solve the error. Also, this issue isn’t related to omnizart itself, but colab environment, which is not what we can control.
