### ISSUE TITLE
Drop support for Python 3.6?

### ISSUE THREAD

**Issue by schneiderfelipe** [Music-and-Culture-Technology-Lab/omnizart#69]
[Python 3.6 was released five years ago and has reached end-of-life in 2021](https://endoflife.date/python). Unless there's a need for omnizart to support legacy environments, I think it would be OK to drop support for Python 3.6? (Related to #67.)

**Comment by BreezeWhite** [comment]
The majority of the python users still use py3.6 as summarized in this page: [https://w3techs.com/technologies/history_details/pl-python/3](https://w3techs.com/technologies/history_details/pl-python/3). So I would suggest not to exclude the support of py3.6.

**Comment by schneiderfelipe** [comment]
> The majority of the python users still use py3.6 as summarized in this page: https://w3techs.com/technologies/history_details/pl-python/3. So I would suggest not to exclude the support of py3.6.

I didn't know that, thanks for the link! Two things I learned from it:
- Python 3.6 should actually be supported in general, even though it already reached end-of-life
- Supporting Python 3.6-3.8 actually covers 84% of users as of May 2022!

This settles the issue. Closing.
