### ISSUE TITLE
Support Python 3.9 (and maybe 3.10?)

### ISSUE THREAD

**Issue by schneiderfelipe** [Music-and-Culture-Technology-Lab/omnizart#70]
As a follow-up to #69, it would be nice to have support for Python 3.9+, which is forbidden in [pyproject.toml](https://github.com/Music-and-Culture-Technology-Lab/omnizart/blob/86bd36353e3eb410b5db3c18ef05f31dabfb0c7f/pyproject.toml):

https://github.com/Music-and-Culture-Technology-Lab/omnizart/blob/86bd36353e3eb410b5db3c18ef05f31dabfb0c7f/pyproject.toml#L26

Although there might be a reason why Python 3.9 is not currently supported. On the other hand, it seems to be very much used: a quick [search at the Ubuntu packages directory](https://packages.ubuntu.com/search?keywords=python3&searchon=names&exact=1&suite=all&section=all) shows that Python 3.9 is the default version in Ubuntu 21.10, and Python 3.10 is the default one in Ubuntu 22.04 (recently launched).

(Thanks for the amazing project by the way!)

**Comment by BreezeWhite** [comment]
Python 3.9 is not included is because of the underlying dependency issues. More specifically because of `spleeter` and `tensorflow`.

**Comment by schneiderfelipe** [comment]
Thanks for the reply. [Python 3.9 support seems to have been added to spleeter in v2.3.0](https://github.com/deezer/spleeter/commit/cefd1c59b1bdb46a781de91bc03e1952485387e9). But indeed we'll have to wait until tensorflow v2.9.0 to get support for Python 3.9 ([support seems to have been added to v2.9.0-rc2](https://github.com/tensorflow/tensorflow/commit/771f93bd9e1a62036217e1958bb272682923d28c), not released yet).

**Comment by BreezeWhite** [comment]
Same as #69.

**Comment by schneiderfelipe** [comment]
> Same as #69.

Should I close this issue?

**Comment by BreezeWhite** [comment]
> Should I close this issue?

Yes, please.
