### ISSUE TITLE
Google Collab is dead

### ISSUE THREAD

**Issue by Alx-AI** [Music-and-Culture-Technology-Lab/omnizart#76]
The links to the colab on both the github and website are dead-ends, any chance those could be reinstated anytime soon?

Thanks for all your work on this incredible tool.

**Comment by BreezeWhite** [comment]
Hi, thanks for reporting the issue. I will fix it as soon as possible.

**Comment by aleph23** [comment]
Or, is the old notebook file available somewhere?  Perhaps in another branch?  Thanks.

**Comment by BreezeWhite** [comment]
Hey all, I've updated the source and the link. The colab should be back now.
