### ISSUE TITLE
Installed on Windows but unable to run omnizart chord transcribe

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [Music-and-Culture-Technology-Lab/omnizart#78]
Tried to install `vamp` using python`2.7` x86 yet still like if It doesn't affect python`3.8`:
This is the returned error: 

> omnizart chord transcribe "C:\Users\MohammedMehdiTBER\Music\Mohammed Al-Haddad\Malak Ghair Allah (You Have No One Except Allah)\[03] Rouhi we Zadi [Malak Ghair Allah (You Have No One Except Allah)] [Mohammed Al-Haddad].flac"
> RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xd
> Traceback (most recent call last):
>   File "C:\Program Files\Python38\Scripts\omnizart-script.py", line 33, in <module>
>     sys.exit(load_entry_point('omnizart==0.5.0', 'console_scripts', 'omnizart')())
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Program Files\Python38\lib\site-packages\omnizart-0.5.0-py3.8.egg\omnizart\cli\chord\transcribe.py", line 16, in transcribe
>     chord.app.transcribe(input_audio, model_path=model_path, output=output)
>   File "C:\Program Files\Python38\lib\site-packages\omnizart-0.5.0-py3.8.egg\omnizart\utils.py", line 328, in __getattr__
>     module = self._load()
>   File "C:\Program Files\Python38\lib\site-packages\omnizart-0.5.0-py3.8.egg\omnizart\utils.py", line 313, in _load
>     module = importlib.import_module(self.__name__)
>   File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\Program Files\Python38\lib\site-packages\omnizart-0.5.0-py3.8.egg\omnizart\chord\__init__.py", line 32, in <module>
>     from omnizart.chord.app import ChordTranscription
>   File "C:\Program Files\Python38\lib\site-packages\omnizart-0.5.0-py3.8.egg\omnizart\chord\app.py", line 14, in <module>
>     from omnizart.feature.chroma import extract_chroma
>   File "C:\Program Files\Python38\lib\site-packages\omnizart-0.5.0-py3.8.egg\omnizart\feature\chroma.py", line 1, in <module>
>     import vamp
>   File "C:\Program Files\Python38\lib\site-packages\vamp\__init__.py", line 163, in <module>
>     import vampyhost
> ImportError: numpy.core.multiarray failed to import

**Comment by BreezeWhite** [comment]
This is an known issues as pointed in issue #6.
