### ISSUE TITLE
Drum transcription does not output CSV file

### ISSUE THREAD

**Issue by hikizisa** [Music-and-Culture-Technology-Lab/omnizart#79]
Currently, drum transcription does not output CSV files even when the output parameter is specified
For the beat and chord transcription, the default behavior seems to be outputting both .mid and .csv files, when the output parameter is given.

https://github.com/Music-and-Culture-Technology-Lab/omnizart/blob/c17b4d268486e76e182a5776be407395f2a8ff2f/omnizart/beat/app.py#L80-L83

https://github.com/Music-and-Culture-Technology-Lab/omnizart/blob/c17b4d268486e76e182a5776be407395f2a8ff2f/omnizart/chord/app.py#L87-L90

However, drum transcription does not provide a way to export the result as a CSV file while github page mentions a CSV export option for the drum transcription as well. Doing the same thing like the chord and beat transcription would be consistent and enable the export option as a CSV file.

**Comment by BreezeWhite** [comment]
Hi, the document states there will only be a MIDI file output as highlighted in yellow.

![螢幕擷取畫面 2022-10-18 131545](https://user-images.githubusercontent.com/24308057/196341587-373478f9-7535-4ea2-94e3-32d8e028c4d4.png)

> github page mentions a CSV export option

I assume you are mislead by the description as highlighted in green in the above screenshot. Currently the drum transcription doesn't output CSV file, only MIDI file will be written out as highlighted in yellow.

The MIDI file could be easily interpreted and transformed into any form you want. Here is code snippet for doing the transformation.

``` python
import csv
import pretty_midi
from enum import Enum

class DrumTypePitchEnum(Enum):
    BASS_DRUM = 35
    SNARE = 38
    HIHAT = 42

def write_csv(midi_path, output='./drum.csv'):
    midi = pretty_midi.PrettyMIDI(midi_path)
    fieldnames = ['event_type', 'midi_num', 'start_time', 'end_time']
    with open(output, 'w') as out:
        writer = csv.DictWriter(out, fieldnmaes=fieldnames)
        writer.writeheader()
        for inst in midi.instruments:
            for note in inst.notes:
                row = {
                    'event_type': DrumTypePitchEnum(note.pitch).name,
                    'midi_num': note.pitch,
                    'start_time': note.start,
                    'end_time': note.end,
                }
                writer.writerow(row)
```

Hope this helps.

**Comment by JiaYK** [comment]
Thank you very much for the script you provided. The issue with the CSV has indeed puzzled me for a long time. I just have a small question: there's a typo here, fieldnmaes=fieldnames.
```python
import csv
import pretty_midi
from enum import Enum

class DrumTypePitchEnum(Enum):
    BASS_DRUM = 35
    SNARE = 38
    HIHAT = 42

def write_csv(midi_path, output='./drum.csv'):
    midi = pretty_midi.PrettyMIDI(midi_path)
    fieldnames = ['event_type', 'midi_num', 'start_time', 'end_time']
    with open(output, 'w') as out:
        writer = csv.DictWriter(out, fieldnames=fieldnames)
        writer.writeheader()
        for inst in midi.instruments:
            for note in inst.notes:
                row = {
                    'event_type': DrumTypePitchEnum(note.pitch).name,
                    'midi_num': note.pitch,
                    'start_time': note.start,
                    'end_time': note.end,
                }
                writer.writerow(row)
```
