### ISSUE TITLE
Drum transcribe result is terrible for electronic music

### ISSUE THREAD

**Issue by atodniAr** [Music-and-Culture-Technology-Lab/omnizart#80]
Used default drum_keras model. Some sample results in zip:

[omnizart-drum-transcribe.zip](https://github.com/Music-and-Culture-Technology-Lab/omnizart/files/9887465/omnizart-drum-transcribe.zip)

**Comment by BreezeWhite** [comment]
This expected since the model was trained on pop music, not electronic music. The model will predict hihat, snare drum, and bass drum these three types only.
