### ISSUE TITLE
Chord Transcribe Not Working

### ISSUE THREAD

**Issue by SinichiKudo02** [Music-and-Culture-Technology-Lab/omnizart#95]
Can you please fix the chord transcribe. When i run it, it gave me an error that the numpy api scripts uses 0xe but the one installed is 0xd

**Comment by ElijaRock** [comment]
I'm getting `RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xd . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .'

**Comment by BreezeWhite** [comment]
If you are using colab, the issue should be fixed now. Run 'pip install numpy==1.23.5' after installing everything should fix the problem.
