### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by tonyy22** [Music-and-Culture-Technology-Lab/omnizart#96]
Hi, 

I got ModuleNotFoundError: No module named 'omnizart' when running the program in Colab. Here are the details:

### Steps to reproduce the problem:

1. Open the Colab link in README
2. Run the "Environment Setup" and "Choose from YouTube" Code boxes and input URL https://www.youtube.com/watch?v=EESoQ-GhKFk&ab_channel=MarzerWong in the blank
3. Run the "Transcribe" Code box. Set the mode to "music-piano-v2"

### Platform

Windows 10

### Browser

Microsoft Edge

#### Environment Setup

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.1.2)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/Music-and-Culture-Technology-Lab/omnizart.git
  Cloning https://github.com/Music-and-Culture-Technology-Lab/omnizart.git to /tmp/pip-req-build-trn_iehu
  Running command git clone --filter=blob:none --quiet https://github.com/Music-and-Culture-Technology-Lab/omnizart.git /tmp/pip-req-build-trn_iehu
  Resolved https://github.com/Music-and-Culture-Technology-Lab/omnizart.git to commit a2f4c614dbac06c8361e40e0d71ae5e24da638af
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click<8.0.0,>=7.1.2 (from omnizart==0.5.0)
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 kB 4.8 MB/s eta 0:00:00
Collecting jsonschema<4.0.0,>=3.2.0 (from omnizart==0.5.0)
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 7.4 MB/s eta 0:00:00
Collecting librosa<0.9.0,>=0.8.0 (from omnizart==0.5.0)
  Downloading librosa-0.8.1-py3-none-any.whl (203 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.8/203.8 kB 17.7 MB/s eta 0:00:00
Collecting madmom<0.17.0,>=0.16.1 (from omnizart==0.5.0)
  Downloading madmom-0.16.1.tar.gz (20.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 65.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting mir_eval<0.7,>=0.6 (from omnizart==0.5.0)
  Downloading mir_eval-0.6.tar.gz (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 kB 11.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow<9.0.0,>=8.3.2 in /usr/local/lib/python3.10/dist-packages (from omnizart==0.5.0) (8.4.0)
Collecting pretty_midi<0.3.0,>=0.2.9 (from omnizart==0.5.0)
  Downloading pretty_midi-0.2.10.tar.gz (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 109.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pyfluidsynth<2.0.0,>=1.2.5 (from omnizart==0.5.0)
  Downloading pyFluidSynth-1.3.2-py3-none-any.whl (19 kB)
Collecting pyyaml<6.0.0,>=5.3.1 (from omnizart==0.5.0)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 21.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting spleeter<3.0.0,>=2.3.0 (from omnizart==0.5.0)
  Downloading spleeter-2.3.2-py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.2/51.2 kB 6.2 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of omnizart to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.4.1 Requires-Python >=3.6, <3.8; 1.4.3 Requires-Python >=3.6, <3.8; 1.4.4 Requires-Python >=3.6, <3.8; 1.4.5 Requires-Python >=3.6, <3.8; 1.4.6 Requires-Python >=3.6, <3.8; 1.4.7 Requires-Python >=3.6, <3.8; 1.4.8 Requires-Python >=3.6, <3.8; 1.4.9 Requires-Python >=3.6, <3.8; 1.5.0 Requires-Python >=3.6, <3.8; 1.5.1 Requires-Python >=3.6, <3.8; 1.5.2 Requires-Python >=3.6, <3.8; 1.5.3 Requires-Python >=3.6, <3.8; 1.5.4 Requires-Python >=3.6, <3.8; 2.0 Requires-Python >=3.6, <3.9; 2.0.1 Requires-Python >=3.6, <3.9; 2.0.2 Requires-Python >=3.6, <3.9; 2.1.1 Requires-Python >=3.6.1,<3.9; 2.1.2 Requires-Python >=3.6.1,<3.9; 2.2.0 Requires-Python >=3.6.1,<3.9; 2.2.1 Requires-Python >=3.6.1,<3.9; 2.2.2 Requires-Python >=3.6.1,<3.9; 2.3.0 Requires-Python >=3.6.1,<3.10; 2.3.1 Requires-Python >=3.6.2,<3.10
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.0 (from omnizart) (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2)
ERROR: No matching distribution found for tensorflow==2.5.0
/bin/bash: omnizart: command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  fluid-soundfont-gm libfluidsynth2 libinstpatch-1.0-2 qsynth
  timgm6mb-soundfont
Suggested packages:
  fluid-soundfont-gs timidity jackd musescore
The following NEW packages will be installed:
  fluid-soundfont-gm fluidsynth libfluidsynth2 libinstpatch-1.0-2 qsynth
  timgm6mb-soundfont
0 upgraded, 6 newly installed, 0 to remove and 13 not upgraded.
Need to get 126 MB of archives.
After this operation, 157 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 fluid-soundfont-gm all 3.1-5.1 [119 MB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 libinstpatch-1.0-2 amd64 1.1.2-2build1 [238 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/universe amd64 timgm6mb-soundfont all 1.3-3 [5,420 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/universe amd64 libfluidsynth2 amd64 2.1.1-2 [198 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal/universe amd64 fluidsynth amd64 2.1.1-2 [25.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 qsynth amd64 0.6.1-1build1 [245 kB]
Fetched 126 MB in 7s (16.9 MB/s)
Selecting previously unselected package fluid-soundfont-gm.
(Reading database ... 123069 files and directories currently installed.)
Preparing to unpack .../0-fluid-soundfont-gm_3.1-5.1_all.deb ...
Unpacking fluid-soundfont-gm (3.1-5.1) ...
Selecting previously unselected package libinstpatch-1.0-2:amd64.
Preparing to unpack .../1-libinstpatch-1.0-2_1.1.2-2build1_amd64.deb ...
Unpacking libinstpatch-1.0-2:amd64 (1.1.2-2build1) ...
Selecting previously unselected package timgm6mb-soundfont.
Preparing to unpack .../2-timgm6mb-soundfont_1.3-3_all.deb ...
Unpacking timgm6mb-soundfont (1.3-3) ...
Selecting previously unselected package libfluidsynth2:amd64.
Preparing to unpack .../3-libfluidsynth2_2.1.1-2_amd64.deb ...
Unpacking libfluidsynth2:amd64 (2.1.1-2) ...
Selecting previously unselected package fluidsynth.
Preparing to unpack .../4-fluidsynth_2.1.1-2_amd64.deb ...
Unpacking fluidsynth (2.1.1-2) ...
Selecting previously unselected package qsynth.
Preparing to unpack .../5-qsynth_0.6.1-1build1_amd64.deb ...
Unpacking qsynth (0.6.1-1build1) ...
Setting up fluid-soundfont-gm (3.1-5.1) ...
Setting up timgm6mb-soundfont (1.3-3) ...
update-alternatives: using /usr/share/sounds/sf2/TimGM6mb.sf2 to provide /usr/share/sounds/sf2/default-GM.sf2 (default-GM.sf2) in auto mode
update-alternatives: using /usr/share/sounds/sf2/TimGM6mb.sf2 to provide /usr/share/sounds/sf3/default-GM.sf3 (default-GM.sf3) in auto mode
Setting up libinstpatch-1.0-2:amd64 (1.1.2-2build1) ...
Setting up libfluidsynth2:amd64 (2.1.1-2) ...
Setting up qsynth (0.6.1-1build1) ...
Setting up fluidsynth (2.1.1-2) ...
Created symlink /etc/systemd/user/multi-user.target.wants/fluidsynth.service → /usr/lib/systemd/user/fluidsynth.service.
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyfluidsynth
  Using cached pyFluidSynth-1.3.2-py3-none-any.whl (19 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pyfluidsynth) (1.22.4)
Installing collected packages: pyfluidsynth
Successfully installed pyfluidsynth-1.3.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2783k  100 2783k    0     0  5331k      0 --:--:-- --:--:-- --:--:-- 5331k

#### Choose from YouTube

Downloading...
/bin/bash: yt-dlp: command not found
/bin/bash: yt-dlp: command not found
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
.mp3: No such file or directory
Finished: 

#### Transcribe

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-da0634d31a82>](https://localhost:8080/#) in <cell line: 12>()
     10 
     11 
---> 12 from omnizart.music import app as mapp
     13 from omnizart.chord import app as capp
     14 from omnizart.drum import app as dapp

ModuleNotFoundError: No module named 'omnizart'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

---------------------------------------------------------------------------

Here, Colab suggested me o install modules manually, so I tried to do it: 

`!pip install omnizart`

The output is like this:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting omnizart
  Downloading omnizart-0.1.0-py3-none-any.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 4.2 MB/s eta 0:00:00
Collecting click<8.0.0,>=7.1.2 (from omnizart)
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 kB 11.6 MB/s eta 0:00:00
Collecting jsonschema<4.0.0,>=3.2.0 (from omnizart)
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 7.6 MB/s eta 0:00:00
Collecting librosa<0.9.0,>=0.8.0 (from omnizart)
  Downloading librosa-0.8.1-py3-none-any.whl (203 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.8/203.8 kB 22.6 MB/s eta 0:00:00
Collecting madmom<0.17.0,>=0.16.1 (from omnizart)
  Downloading madmom-0.16.1.tar.gz (20.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 23.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numba==0.48 (from omnizart)
  Downloading numba-0.48.0.tar.gz (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 51.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: opencv-python<5.0.0,>=4.4.0 in /usr/local/lib/python3.10/dist-packages (from omnizart) (4.7.0.72)
Collecting pretty_midi<0.3.0,>=0.2.9 (from omnizart)
  Downloading pretty_midi-0.2.10.tar.gz (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 104.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pyfluidsynth<2.0.0,>=1.2.5 (from omnizart)
  Downloading pyFluidSynth-1.3.2-py3-none-any.whl (19 kB)
Collecting pyyaml<6.0.0,>=5.3.1 (from omnizart)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 20.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tensorflow<3.0.0,>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from omnizart) (2.12.0)
Requirement already satisfied: tqdm<5.0.0,>=4.49.0 in /usr/local/lib/python3.10/dist-packages (from omnizart) (4.65.0)
Requirement already satisfied: urllib3<2.0.0,>=1.25.11 in /usr/local/lib/python3.10/dist-packages (from omnizart) (1.26.16)
Collecting vamp<2.0.0,>=1.1.0 (from omnizart)
  Downloading vamp-1.1.0.tar.gz (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.8/107.8 kB 14.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting llvmlite<0.32.0,>=0.31.0dev0 (from numba==0.48->omnizart)
  Downloading llvmlite-0.31.0.tar.gz (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 kB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.10/dist-packages (from numba==0.48->omnizart) (1.22.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from numba==0.48->omnizart) (67.7.2)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema<4.0.0,>=3.2.0->omnizart) (23.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema<4.0.0,>=3.2.0->omnizart) (0.19.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema<4.0.0,>=3.2.0->omnizart) (1.16.0)
Requirement already satisfied: audioread>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.9.0,>=0.8.0->omnizart) (3.0.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.9.0,>=0.8.0->omnizart) (1.10.1)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.9.0,>=0.8.0->omnizart) (1.2.2)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.10/dist-packages (from librosa<0.9.0,>=0.8.0->omnizart) (1.2.0)
Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.9.0,>=0.8.0->omnizart) (4.4.2)
Collecting resampy>=0.2.2 (from librosa<0.9.0,>=0.8.0->omnizart)
  Downloading resampy-0.4.2-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 119.4 MB/s eta 0:00:00
Requirement already satisfied: soundfile>=0.10.2 in /usr/local/lib/python3.10/dist-packages (from librosa<0.9.0,>=0.8.0->omnizart) (0.12.1)
Requirement already satisfied: pooch>=1.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.9.0,>=0.8.0->omnizart) (1.6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.9.0,>=0.8.0->omnizart) (23.1)
Requirement already satisfied: cython>=0.25 in /usr/local/lib/python3.10/dist-packages (from madmom<0.17.0,>=0.16.1->omnizart) (0.29.35)
Collecting mido>=1.2.8 (from madmom<0.17.0,>=0.16.1->omnizart)
  Downloading mido-1.2.10-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 kB 6.8 MB/s eta 0:00:00
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (23.5.26)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (1.54.2)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (0.4.10)
Requirement already satisfied: keras<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (2.12.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (16.0.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (3.3.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (3.20.3)
Requirement already satisfied: tensorboard<2.13,>=2.12 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (2.12.3)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (2.12.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (4.6.3)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<3.0.0,>=2.3.0->omnizart) (0.32.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow<3.0.0,>=2.3.0->omnizart) (0.40.0)
Requirement already satisfied: ml-dtypes>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow<3.0.0,>=2.3.0->omnizart) (0.2.0)
Requirement already satisfied: appdirs>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from pooch>=1.0->librosa<0.9.0,>=0.8.0->omnizart) (1.4.4)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from pooch>=1.0->librosa<0.9.0,>=0.8.0->omnizart) (2.27.1)
INFO: pip is looking at multiple versions of resampy to determine which version is compatible with other requirements. This could take a while.
Collecting resampy>=0.2.2 (from librosa<0.9.0,>=0.8.0->omnizart)
  Downloading resampy-0.4.1-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 103.9 MB/s eta 0:00:00
  Downloading resampy-0.4.0-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 111.7 MB/s eta 0:00:00
  Downloading resampy-0.3.1-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 121.5 MB/s eta 0:00:00
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa<0.9.0,>=0.8.0->omnizart) (3.1.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.10/dist-packages (from soundfile>=0.10.2->librosa<0.9.0,>=0.8.0->omnizart) (1.15.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (3.4.3)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (2.3.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0->soundfile>=0.10.2->librosa<0.9.0,>=0.8.0->omnizart) (2.21)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (1.3.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa<0.9.0,>=0.8.0->omnizart) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa<0.9.0,>=0.8.0->omnizart) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa<0.9.0,>=0.8.0->omnizart) (3.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (2.1.3)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow<3.0.0,>=2.3.0->omnizart) (3.2.2)
Building wheels for collected packages: numba, madmom, pretty_midi, pyyaml, vamp, llvmlite
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for numba (setup.py) ... error
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for madmom (setup.py) ... done
  Created wheel for madmom: filename=madmom-0.16.1-cp310-cp310-linux_x86_64.whl size=21509065 sha256=5872e8240ee44eb865b42dd7a6f1658ca162a59903d91aa2c099f558be824689
  Stored in directory: /root/.cache/pip/wheels/87/18/20/105f9248e5f504f5ab190338516558cacaf6d5d7fadd5e7947
  Building wheel for pretty_midi (setup.py) ... done
  Created wheel for pretty_midi: filename=pretty_midi-0.2.10-py3-none-any.whl size=5592289 sha256=285ee60d28566b1cb30cd66d91a0f81428aa427a15a3a55c3f9ce9c5917bd81e
  Stored in directory: /root/.cache/pip/wheels/cd/a5/30/7b8b7f58709f5150f67f98fde4b891ebf0be9ef07a8af49f25
  Building wheel for pyyaml (pyproject.toml) ... done
  Created wheel for pyyaml: filename=PyYAML-5.4.1-cp310-cp310-linux_x86_64.whl size=45658 sha256=ebecb13dbaf89828b5991920ef08837fec988b4727e891e6c21e7d6d959db043
  Stored in directory: /root/.cache/pip/wheels/c7/0d/22/696ee92245ad710f506eee79bb05c740d8abccd3ecdb778683
  Building wheel for vamp (setup.py) ... done
  Created wheel for vamp: filename=vamp-1.1.0-cp310-cp310-linux_x86_64.whl size=1690114 sha256=4bbd021deff266f16cfab101cabc44e5427abb877c49d65aefdccd6f4098d118
  Stored in directory: /root/.cache/pip/wheels/36/9e/b1/230ac612a8aa718cf3e2485eac386ae72a4da61d7c31ac4bb2
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built madmom pretty_midi pyyaml vamp
Failed to build numba llvmlite
ERROR: Could not build wheels for numba, llvmlite, which is required to install pyproject.toml-based projects

After which, I could not run the code in part "Transcribe"

Could anybody tell me how to solve it?

**Comment by BreezeWhite** [comment]
After digging into the issue, it looks like it's a compatibility issue, which `omnizart` assumes using python < 3.9, and the colab itself now default to use python3.10. I've update the colab to use an older version of python and it should work now.
